# Generated by Django 2.2 on 2020-06-12 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200612_0842'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phto',
            new_name='Photo',
        ),
    ]
