# Generated by Django 2.2 on 2020-07-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200612_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='date_reservated',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
