# Generated by Django 2.2 on 2020-07-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_shippingaddress_date_reservated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservated', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
