# Generated by Django 2.2 on 2021-01-06 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20200807_0449'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='family_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.FamilyPhoto'),
        ),
    ]
