# Generated by Django 2.2 on 2021-01-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_orderitem2'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
