# Generated by Django 2.2 on 2021-01-09 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210108_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem2',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem2',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='family_photo',
        ),
        migrations.DeleteModel(
            name='FamilyPhoto',
        ),
        migrations.DeleteModel(
            name='OrderItem2',
        ),
    ]
