# Generated by Django 2.2 on 2021-01-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_familybwframe_familybwphoto_familyframe'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyReservationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservated', models.CharField(max_length=200, null=True)),
                ('complete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
