# Generated by Django 2.2 on 2021-01-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_familyreservationdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familybwframe',
            options={'ordering': ['price']},
        ),
        migrations.AddField(
            model_name='familyreservationdata',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
