# Generated by Django 2.2 on 2021-03-26 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20210128_0911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familyframe',
            options={'ordering': ['price']},
        ),
    ]
