# Generated by Django 2.2 on 2021-03-26 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_hanbokdb_hanboks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hanboks',
            options={'ordering': ['-id']},
        ),
    ]
